### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by stephanepericat**
As discussed

### CODE REVIEW

**Comment by dragoverde** [comment]
1) pom.xml - fix indentation
2) all local widget/container readme files should have the "Additional resources" section listing all additional resources:
    - feed widget a: xsl, ptc config, import xml
    - feed widget b: transformer, ptc config, import xml
    - content widget: css/templates.css, templates/content, import xml
    - custom chrome: uiEditionOptions.js
3) root readme file should include steps 1-3 from usage.txt in the "Configuration" section

**Comment by stephanepericat** [comment]
@dragoverde changes made as discussed. Please review.

**Comment by stephanepericat** [comment]
Added the "additional resources" as required in your comment

**Comment by dragoverde** [comment]
many files still have indentation problems

**Comment by stephanepericat** [comment]
@dragoverde 

For indentation problems, there is not much I can do... different files written by different people with different indentation settings on different operating systems... Can you please point to a few specific files that you absolutely want to see indented properly ?

**Comment by stephanepericat** [comment]
@dragoverde fix indent for all js and html files

**Comment by dragoverde** [comment]
Everything is fine

**Pull request merged**
